### ISSUE TITLE
More than one file was found with OS independent path 'lib/armeabi-v7a/libfreetype.so'

### ISSUE THREAD

**Issue by gantulgana93** [flyskywhy/react-native-particles-bg#1] opened 2021-01-13 07:01 UTC
Any help please

**Comment by flyskywhy** [comment] 2021-01-17 02:26
duplicate of https://github.com/flyskywhy/react-native-gcanvas/issues/6

**Closed as completed by flyskywhy** 2021-01-17 02:26 UTC

**Comment by flyskywhy** [comment] 2021-06-25 00:06
Fixed with  react-native-particles-bg@3.0.3 and @flyskywhy/react-native-gcanvas@2.3.2
